apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: http-service-dev
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/jarom-w/sample_http
    targetRevision: main
    path: charts/http_service
    helm:
      valueFiles:
        - ../../environments/http_service/dev/http-service.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
