apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: http-service-staging
  namespace: argocd
spec:
  project: default

  sources:
    #Application repo (Helm chart)
    - repoURL: https://github.com/jarom-w/sample_http
      targetRevision: main
      path: charts/http_service

    - repoURL: https://github.com/jarom-w/promote_pipeline
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: staging

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
